services:
  server:
    image: ghcr.io/merofuruya/shelly-metrics
    restart: always
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=shelly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shelly
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
